[build]
    functions = "functions"

[[redirects]]
    to="/.netlify/functions/api/:splay"
    from="/api/*"
    status=200

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"